#!/bin/sh
INTERVAL=60
echo "restart all instances and sleep for $INTERVAL seconds in between"
bin/supervisorctl restart instance1
sleep $INTERVAL
bin/supervisorctl restart instance2
sleep $INTERVAL
bin/supervisorctl restart instance3
sleep $INTERVAL
bin/supervisorctl restart instance4
sleep $INTERVAL
bin/supervisorctl restart instancebots
echo "finished"
